### PR TITLE
Add README

### PR DESCRIPTION
**Pull request by nelsonmestevao**
Leave some ideas of what I could explain more and better, please :pray:

### CODE REVIEW

**Comment by protodan** [comment]
Hi Nelson!

I would write a paragraph on the beginning on the following lines (feel free to rewrite, did not check the grammar):
```
## Introduction
Sometimes there are benefits on writing unit tests for your solutions both while training and in competition setups. One of the goals of this repo is to simplify that process.

In order to do so, hereby is provided a class that enables the automatic execution and debugging of your code using test cases provided in text files.

[EXAMPLE]
```
Maybe you could add a section on Tips (e.g. a shortcuts to run the TextExecutor and set breakpoints).
 
Additionally, a gif with the process of using this tool (or a description of the series of steps) would be valuable for the rookies (in the `[EXAMPLE]` part of the introduction).

Anyway, this readme is something that will be improved along the times, so do pls do not feel like it has to be perfect right now.

What do you think?

**Comment by nelsonmestevao** [comment]
Thank you for your feedback. I will take it in account and improve upon it.

I will definitely add the introduction and a gif, as suggested.

**Comment by nelsonmestevao** [comment]
demo

**Comment by nelsonmestevao** [comment]
demo

**Comment by nelsonmestevao** [comment]
@protodan what do you think of this one for starting? I removed the WIP tag from the PR.

**Comment by protodan** [comment]
LGTM! feel free to merge it

**Pull request merged**
